
# The name of your website.
name: Francesco Improta

description:

  # Description of your site. This will show up in google.
  meta: Personal website of Francesco Improta, product designer from Rome, Italy. Write about design, front-end and building stuff on the web.

  # Description of your site. This will show up on the front page.
  subtitle: Blog about design, front-end and making things on the web. Edited by Francesco Improta.

author:
  name: Francesco Improta

  # Necessary for contact page
  email: me@francescoimprota.com
  twitter: zetareticoli
 
url: http://francescoimprota.com
baseurl: ""

# language attribute in <html> element.
lang: en

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

sass:
  sass_dir: _sass
  style: compressed

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: false
display-social-icons: false
# If you want social links to open in a new tab, set this as true
social-icons-open-newtab: true

footer-text: Designed with <a href="#" class="link-alt">Figma</a>. Powered by <a class="link-alt" href="#">Jekyll</a> &amp; <a class="link-alt" href="#">Netlify</a>. Font <a class="link-alt" href="https://rsms.me/inter/">Inter</a> by <a class="link-alt" href="https://twitter.com/rsms">@rsms</a>

# Preferably 64px in height. Leave empty = disable.
logo-image: /img/logo.svg

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 0, 240, 255 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: false
display-author-front-page: false

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 3

# Display links for the previous and next post on post pages.
display-next-prev-post: true

##############
# CONTENT #
##############

navigation:
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Work
  url: /work/
- text: Portfolio
  url: http://zetareticoli.dribbble.com
  external: true
- text: Workshop
  url: /workshop/


projects:
- title: CSSUI
  desc: Pure CSS interactive components 
  url: https://www.github.com/zetareticoli/cssui
  color: teal
  downloads: 1.2k
- title: Typesmith
  desc: A responsive typography library
  url: https://www.github.com/zetareticoli/typesmith
  color: orange
  downloads: 369
- title: Superilles
  desc: Grid system with CSS Grid
  url: https://www.github.com/zetareticoli/superilles
  color: purple
- title: Sass MQ
  desc: A simple media query library for Sass
  url: https://www.github.com/zetareticoli/mq
  color: purple
- title: UIKit Starter kit
  desc: UI Design Kit template for Sketch
  url: https://www.github.com/zetareticoli/uikit-starter
  color: blue
  
#####################
# SOCIAL #
#####################

twitter_username: zetareticoli

#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Read # Text after each post summary on the homepage.
var_newer: Newer
var_older: Older
var_next_post: Next post
var_previous_post: Previous post
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: Your email
var_your_message: Your message


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: ['vendor', 'node_modules']
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
