
# The name of your website.
name: Francesco Improta

description:

  # Description of your site. This will show up in google.
  meta: Personal website of Francesco Improta, product designer from Rome, Italy. Write about design, front-end and building stuff on the web.

  # Description of your site. This will show up on the front page.
  subtitle: Blog about design, front-end and making things on the web. Edited by Francesco Improta.

author:
  name: Francesco Improta

  # Necessary for contact page
  email: me@francescoimprota.com
  twitter: zetareticoli
 
url: http://francescoimprota.com
baseurl: ""

# language attribute in <html> element.
lang: en

collections: 
  work:
    output: true

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

sass:
  sass_dir: _sass
  style: compressed

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: false
display-social-icons: false
# If you want social links to open in a new tab, set this as true
social-icons-open-newtab: true

footer-text: Designed with Figma. Powered by Jekyll &amp; Netlify. Font Mona Sans by <a class="link-light link-underline" href="https://github.com/mona-sans" target="_blank">Github</a>

# Preferably 64px in height. Leave empty = disable.
logo-image: /img/logo.svg

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

display-author-post-page: false
display-author-front-page: false

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
date_format: "%b %-d, %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
paginate: 3

# Display links for the previous and next post on post pages.
display-next-prev-post: true

##############
# CONTENT #
##############

navigation:
- text: About
  url: /about/
- text: Writing
  url: /writing/
- text: Work
  url: /work/
- text: Side projects
  url: /projects/

#####################
# SOCIAL #
#####################

twitter_username: zetareticoli

#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: On the web
var_read: Read # Text after each post summary on the homepage.
var_newer: Newer
var_older: Older
var_next_post: Next post
var_previous_post: Previous post
var_less_than_a_minute_read: Less than a minute read
var_min_read: min read # Text after reading time. Example: 5 min read.
var_post_by: Post by
var_guest_post_by: Guest post by
var_your_email: Your email
var_your_message: Your message


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: ['vendor', 'node_modules']
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
